In [10]:
import pandas as pd
import time
import warnings

In [11]:
pd.set_option('display.max_columns', None)
warnings.filterwarnings('ignore')

In [12]:
url = "https://redfin-public-data.s3.us-west-2.amazonaws.com/redfin_market_tracker/city_market_tracker.tsv000.gz"

In [13]:
# start time to read file
startTime = time.time()
df = pd.read_csv(url, compression='gzip', sep='\t') #, on_bad_lines='skip')
# end time 
executionTime = (time.time() - startTime)
print('Execution time in minutes: ' + str(round(executionTime / 60, 2)))
print('Num of rows:', len(df))
print('Num of cols:', len(df.columns))

df.tail()

Execution time in minutes: 70.69
Num of rows: 4303467
Num of cols: 58

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated
4303462,2015-02-01,2015-02-28,30,place,6,2390,f,"Brooklyn, OH",Brooklyn,Ohio,OH,All Residential,-1,99500.0,0.273600,-0.342149,79900.0,-0.111235,-0.102247,72.601010,0.122202,0.038205,74.010152,-0.110890,-0.095431,9.0,-0.100000,3.500000,6.0,0.200000,0.500,11.0,0.222222,0.222222,34.0,0.030303,-0.028571,3.8,0.5,-13.7,56.0,-42.0,-69.0,0.947263,0.015028,-0.040832,0.222222,0.122222,0.222222,NaN,NaN,NaN,0.166667,-0.233333,-0.333333,"Cleveland, OH",17460,2022-09-11 14:46:03
4303463,2022-01-01,2022-01-31,30,place,6,29748,f,"Milton, MA",Milton,Massachusetts,MA,Multi-Family (2-4 Unit),4,1100000.0,0.062802,NaN,862450.0,NaN,NaN,362.796834,-0.064089,NaN,471.744370,NaN,NaN,1.0,0.000000,NaN,1.0,-0.500000,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,-1.0,NaN,1.158017,-0.059774,NaN,1.000000,0.000000,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,"Boston, MA",14454,2022-09-11 14:46:03
4303464,2017-12-01,2017-12-31,30,place,6,16802,f,"Portage, MI",Portage,Michigan,MI,Condo/Co-op,3,118000.0,-0.551898,0.000000,259000.0,0.619762,0.138712,98.169717,-0.202614,0.031166,113.636364,0.092457,0.023924,9.0,-0.181818,0.285714,6.0,0.500000,-0.250,4.0,0.000000,0.333333,11.0,-0.214286,-0.521739,1.2,-0.1,-2.1,70.0,23.0,19.0,0.986421,-0.019001,0.016134,0.222222,-0.050505,0.222222,0.181818,-0.318182,0.13834,0.500000,0.250000,0.500000,"Kalamazoo, MI",28020,2022-09-11 14:46:03
4303465,2019-01-01,2019-01-31,30,place,6,13410,f,"New Haven, CT",New Haven,Connecticut,CT,Condo/Co-op,3,99500.0,-0.320819,0.005051,189900.0,0.063866,0.117716,99.644271,-0.273427,-0.009385,111.363857,0.243795,0.259978,14.0,0.076923,0.400000,5.0,-0.444444,-0.375,22.0,2.142857,0.222222,71.0,0.109375,-0.077922,5.1,0.2,-2.6,66.0,-105.0,0.0,0.964721,0.035217,0.022524,0.142857,0.142857,0.042857,0.140845,0.015845,0.07591,0.200000,0.200000,-0.050000,"New Haven, CT",35300,2022-09-11 14:46:03
4303466,2015-06-01,2015-06-30,30,place,6,16755,f,"Soap Lake, WA",Soap Lake,Washington,WA,All Residential,-1,135000.0,0.000741,0.350000,224000.0,0.875262,0.866667,49.423394,-0.446048,-0.518878,102.377392,0.170585,-0.007147,5.0,0.666667,0.000000,3.0,0.500000,-0.250,6.0,0.000000,-0.250000,28.0,0.000000,0.037037,5.6,-3.7,0.2,168.0,42.0,92.0,0.870580,-0.153998,-0.044328,0.000000,-0.333333,0.000000,0.214286,-0.035714,NaN,0.000000,-0.500000,-0.750000,"Moses Lake, WA",34180,2022-09-11 14:46:03

In [9]:
5

5